name: Build PrusaSlicer AppImage
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 1 * * *' # every Day at 01:00
permissions:
  actions: write
  contents: write
defaults:
  run:
    shell: bash
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  linux:
    runs-on: ubuntu-latest
    #timeout-minutes: 180
    steps:
    - name: Setup Env
      run: |
        #set -x
        LINK_REPO="realthunder/FreeCAD"
        THIS_REPO_DIR=${GITHUB_WORKSPACE}/${GITHUB_REPOSITORY##*/}
        TOOLS_DIR=${THIS_REPO_DIR}/.github/tools
        APPIMAGETOOL="${TOOLS_DIR}/appimagetool-x86_64.AppImage"

        for i in LINK_REPO THIS_REPO_DIR TOOLS_DIR APPIMAGETOOL; do
          eval "r=\"\$$i\""
          echo "$i=$r" >> $GITHUB_ENV
        done

    - name: Check Releases and Skip Rest of Job if no new release
      id: Check_Releases
      run: |
        #set -x
        #set -v
        GetReleases()
         {
          list=$(gh release list -R "$1" --json tagName | jq -r 'map(select(true))[] | (.tagName)')
          tmpfile=mktemp
          touch $tmpfile
          for i in $list; do
            if [[ $i == *stable ]] && dpkg --compare-versions $i "ge" "20241003stable"; then
              echo $i >>$tmpfile
            fi
          done
          sort <$tmpfile >$2
          rm -f $tmpfile
         }
        
        GetReleases "$LINK_REPO" "./Link.Releases"
        GetReleases "$GITHUB_REPOSITORY" "./This.Releases"
        VERSION=$(head -1 <<< "$(comm -23 Link.Releases This.Releases)")
        rm -f "./Link.Releases" "./This.Releases"
        
        if [ -z "${VERSION}" ]; then
          echo "No new release found. Skipping rest of workflow."
          echo "skip=true" >> $GITHUB_OUTPUT
         else
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "New release found: ${VERSION}"
          echo "skip=false" >> $GITHUB_OUTPUT
        fi

    - name: Clone this repository
      if: steps.Check_Releases.outputs.skip == 'false'
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Get FreeCAD AppImage
      if: steps.Check_Releases.outputs.skip == 'false'
      run: |
        VERSION_NR=${VERSION%%stable}
        IN_FILE=FreeCAD-Link-Stable-Linux-x86_64-py3.11-${VERSION_NR}.AppImage
        OUT_FILE=FreeCAD-Link-Stable-GN-${VERSION_NR}.AppImage
        
        wget -q https://github.com/realthunder/FreeCAD/releases/download/${VERSION}/${IN_FILE}
        set -x
        set -v
        chmod a+x ${IN_FILE}
        ./${IN_FILE} --appimage-extract >/dev/null
        cp ${TOOLS_DIR}/AppRun.Link squashfs-root/AppRun
        rm -f squashfs-root/usr/share/metainfo/org.freecadweb.FreeCAD.Link.appdata.xml
        ARCH=x86_64 ${APPIMAGETOOL} squashfs-root/ ${OUT_FILE} >/dev/null
        rm ${IN_FILE}
        
        # Upload to GitHub Releases
        list=$(gh release list -R "$1" --json tagName | jq -r 'map(select(true))[] | (.tagName)');
        for i in $list; do
          if [ "$i" = "${VERSION}" ]; then
            gh release delete $VERSION -y
          fi
        done
        gh release create $VERSION *.AppImage* --title "$VERSION"
        
        #https://github.com/realthunder/FreeCAD/releases/download/20241003stable/FreeCAD-Link-Stable-Linux-x86_64-py3.11-20241003.AppImage
        #https://github.com/realthunder/FreeCAD/releases/download/20240322stable/FreeCAD-Link-Stable-Linux-x86_64-py3.11-20240322.AppImage

